### PR TITLE
Update git-version to 2.42.0 from 2.41.0

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Comment by v1gnesh** [comment]
The next steps are:

- [ ] https://github.com/ZOSOpenTools/meta/pull/437
- [ ] Maybe setup commit signing for `zosopentoolsmain` (and other security such as 2FA or whatever applies to a bot account)
- [ ] Trigger a pre-release build for PRs created by `zosopentoolsmain` where a version change is suggested. Best to pass both conditions as the ID may be used for other automated workflows in the future.

**Comment by IgorTodorovskiIBM** [comment]
Build failed, will require updating:
```
***ERROR: Patch of make tree failed (/jenkins/PortBuild/git/patches/./cache.h.patch).
```

**Comment by IgorTodorovskiIBM** [comment]
Addressed in https://github.com/ZOSOpenTools/gitport/pull/99

**Pull request closed without merging**
