### PR TITLE
Update git-version to 2.43.0 from 2.42.1

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Comment by IgorTodorovskiIBM** [comment]
/jenkins/PortBuild/git/stable-patches/./environment.h.patch fails to apply

**Comment by IgorTodorovskiIBM** [comment]
@HarithaIBM do you want to look into this?

**Comment by HarithaIBM** [comment]
> @HarithaIBM do you want to look into this?

Yes , I am analysing this Igor!

**Comment by HarithaIBM** [comment]
Fix is merged

**Pull request closed without merging**
