### PR TITLE
bump fix - git-version to 2.43.0 from 2.42.1

### PR DESCRIPTION
**Pull request by HarithaIBM**

### CODE REVIEW

**Comment by HarithaIBM** [comment]
fix for https://github.com/ZOSOpenTools/gitport/pull/102

**Comment by v1gnesh** [comment]
A suggestion: could the titles be something like "add/update patch(es) for 2.43.0".
With the rate at which bump is pulling in updates, we'll have too many commits/PRs with the same name otherwise :sweat_smile:

**Comment by HarithaIBM** [comment]
cacert issue

**Comment by v1gnesh** [comment]
@IgorTodorovskiIBM @HarithaIBM Just wondering... for neatness or housekeeping, is it possible to work on the branch that bump creates and push the fixes/updates through that branch itself?

**Pull request merged**
